config/routes.rb
Rails.application.routes.draw do
  root "welcome#welcome"
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  resources :users do
    resources :products do
      resources :orders 
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user
  validates :shipping_address, presence: true
  validates :transaction_id, uniqueness: true
end

app/models/product.rb
# Model Product
class Product < ApplicationRecord
  belongs_to :user, optional: true
  has_one_attached :product_image
  has_many :orders, dependent: :destroy
  validates :name, presence: true
  validates :detail, presence: true
  validate :acceptable_image

  private

  def acceptable_image
    return unless product_image.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Associated with products and orders
  has_secure_password
	has_many :products
  has_many :orders
  # validation for user registration 
  validates :name, presence: true
  validates :email, uniqueness: true
  validates :password, length: { in: 5..10 }
  validates :role, presence: true
  validates :password_confirmation, confirmation: true
end

app/controllers/application_controller.rb
# Main Controller
class ApplicationController < ActionController::Base
	def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user
	private
	def check_user_authentication
		if current_user.present?
 			flash[:notice] = "you can "
		else
			flash[:notice] = "Please Login First"
			redirect_to login_path
		end
	end
	def match_url_and_session_ids
		if (current_user.id).eql?(params[:user_id])
			flash[:notice] = " yeah you can "
		else
			flash[:notice] = " Sorry you can not access "
			redirect_to root_path
		end
	end
end

app/controllers/orders_controller.rb
# Order Controller for all orders od Customer
class OrdersController < ApplicationController
	# To check User is Logged_in or Not
	before_action :check_user_authentication
	# before_action :match_url_and_session_ids

	def index
		@orders = []
    @orders << Order.where(user_id: current_user.id)
    @orders = @orders.flatten
    @user = params[:user_id]
    @user_detail = User.find(@user)
	end

	def show
	end

	def new
		@order = params
		@product = Product.find(params[:product_id])
		@order = Order.new
	end

	def create
		@order = Order.new(order_params)
		@order.user_id = current_user.id
		@order.product_id = (params[:product_id])
		if @order.save
			redirect_to root_path
		else
			redirect_to new_user_product_order
		end
	end

	private
	def generate_transaction_id
		@order.transaction_id = SecureRandom.hex(10)
	end

	def order_params
		params.require(:order).permit!
	end
end

app/controllers/products_controller.rb
# Product Class for Customer and Admin
class ProductsController < ApplicationController
	# To check User is Logged_in or Not
  before_action :check_user_authentication
	# before_action :match_url_and_session_ids
  # To checking condition for Admin to Create and update Products
  before_action :check_seller, only: [:new, :create]
  before_action :check_seller_for_update, only: [:edit, :update]

  def index
    @products = []
    @products << Product.where(user_id: params[:user_id])
    @products = @products.flatten
    @user = params[:user_id]
    @user_detail = User.find(@user)
  end

  def show
    @product = Product.find(params[:id])
    @user = params[:user_id]
    @user_detail = User.find(@user)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @user_id = params[:user_id]
    @product.user_id = @user_id
    #byebug
    if @product.save
      flash[:notice] = "Your Product is Saved Successfully"
      redirect_to user_product_path(user_id: @user_id, id: @product.id)
    else
      flash[:notice] = "Please try again"
      redirect_to new_user_product(@user_id)
    end
  end

  def edit
    # byebug
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    # byebug
    if @product.update(product_params)
      # byebug
      flash[:notice] = "Product updated"
      redirect_to new_user_product_path 
    else
      flash[:notice] = "Product has not updated"
      redirect_to new_user_product_path 
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :detail, :price, :user_id)
  end
  def match_users
    (current_user.id).to_s.eql?(params[:user_id])
  end
  def check_seller
    if match_users
      if (current_user.role).eql?("seller")
        flash[:notice] = "Yeah you can Update"
      else
        flash[:notice] = "Oops! Its only for Admin Use"
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end
  def match_seller
    @id = (params[:id]).to_i
    @product = Product.find(@id)
    @user_id = @product.user_id
    current_user.id.eql?(@user_id)
  end
  def check_seller_for_update
    if match_seller
      flash[:notice] = "Yeah you can Update"
    else
      flash[:notice] = "Sorry you can not update this Product "
      redirect_to user_products_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :user_already_exist, only: [:new]
  def new
  end
  def create
    user = User.find_by(email: params[:email])
    # byebug
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Login successful"
      redirect_to '/'
    else
      flash[:notice] = "Invalid Email or Password"
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged Out"
    redirect_to '/login'
  end
  private 
  def user_already_exist
    if current_user.present?
      flash[:notice] = " Oops You Are already, Please logout first  " 
      redirect_to root_path
    else

    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :check_user_authentication
  # before_action :getting_id, only: :show
  def index 
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      redirect_to '/login'
      flash[:notice] = "Registered successful"
    else
      flash[:notice] = "Please try again"
      redirect_to signup_path
    end
  end

	private 
  
	def user_params
		params.require(:user).permit(:name, :email, :role, :password, :password_confirmation)
	end
  def getting_id
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
# root or welcome controller 
class WelcomeController < ApplicationController
	def welcome
    @products = Product.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyMobile</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="container" style="height:870px; border:1px solid #800000; color:#800080;">
	<div>
    <h1 style="text-align:center">Welcome to Woo-commerce </h1>
		<h2 style="text-align:center">This is Account History </h2>
		<div class=row>
			<div class="col-11"></div>
			<div class="col-1">
				<h4>	
				<%=  link_to "Home", root_path %>
				</h4>
			</div>
		</div>
		<hr>
	</div>
	<% if @orders.length == 1 %>
		<div class="row">
			<div class="col-4"></div>
			<div class="col-4" style="margin-left:7%; margin-bottom:2.5%; margin-top:2.5%;">
				<h2><%= @orders[0].shipping_address %></h2>
				<h5><%= @orders[0].transaction_id %> </h5>
				<h5><%= @orders[0].amount %>/-</h5>
				<h6><%= @orders[0].created_at %></h6>
			</div>
			<div class="col-4"></div>
		</div>
	<% elsif (@orders.length > 1) %>
		<div class="row">
			<% @orders.each do | order| %>
				<div class="col-3" style="margin-left:7%; margin-bottom:2.5%; margin-top:2.5%;">
					<p>Address:- <%= order.shipping_address %></p>
					<p>Transaction_id:- <%= order.transaction_id %> </p>
					<p>Amount <%= order.amount %>/-</p>
					<h6>Date:- <%= order.created_at %></h6>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/orders/new.html.erb
<div class="container">
	<h1 style="text-align:center"> Buy Your Product</h1><br>
	<div class="row">
		<div class="col-3"></div>
		<div class="col-1" >
			<h2>Product:-</h2>
			<h4>Detail:- </h4>
			<h5>Price:- </h5>
		</div><div class="col-1"></div>
		<div class="col-3" >
			<h2><%= @product.name %></h2>
			<h4><%= @product.detail %> </h4>
			<h5><%= @product.price %>/-</h5>
		</div>
		<div class="col-4"></div>
	</div>
	<%= form_with model: [:user, :product, @order] do |form| %>
	<div class="card">
    <% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
    <% end %>
 		<div class="card-body">
      <div class="mb-3">
        <%= form.label :shipping_address, { class: "form-label"}  %><br>
        <%= form.text_field :shipping_address, { class: "form-control", placeholder: "Enter Shipping Address" } %><br>
      </div>
			<div>
				<%= form.hidden_field :transaction_id, value: SecureRandom.hex(10) %>
			</div>
      <div class="mb-3">
        <%= form.label :Total, { class: "form-label"}  %><br>
        <%= form.select :amount,[ @product.price ]%><br>
      </div>
      <div class="mb-3"><br>
        <%= form.submit "Proceed", { class: "btn btn-primary" }  %>
				<%= link_to "Cancel", root_path, { class: "btn btn-info" } %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/products/_form.html.erb
<%= form_with model: @products, method: :post do |form| %>
<div class="card">
 <div class="card-body">
  <div class="mb-3">
    <%= form.label :name, { class: "form-label"}  %><br>
    <%= form.text_field :name, { class: "form-control", placeholder: "Enter Product Name" } %><br>
    <% product.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div class="mb-3">
    <%= form.label :detail, { class: "form-label"}  %><br>
    <%= form.text_field :detail, { class: "form-control", placeholder: "Enter Product Detail " } %><br>
    <% product.errors.full_messages_for(:detail).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :price, { class: "form-label"}  %><br>
     <%= form.text_field :price, { class: "form-control", placeholder: "Enter Product Price" }  %><br>
    <% product.errors.full_messages_for(:price).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div> 
  <div class="mb-3"><br>
    <%= form.submit "Add Product", { class: "btn btn-primary" }  %>
  </div>
<% end %>

</div>
</div>

app/views/products/edit.html.erb
<div class="container">
	<div>
		<h2>update your product</h2>
	</div>
		<%= form_with model: [:user,@product] do |form| %>
	<div class="card">
    <% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
    <% end %>
 		<div class="card-body">
      <div class="mb-3">
        <%= form.label :name, { class: "form-label"}  %><br>
        <%= form.text_field :name, { class: "form-control", placeholder: "Enter Product Name" } %><br>
        <%
=begin%>
 <% product.errors.full_messages_for(:name).each do |message| %>
          <div><%= message %></div>
        <% end %> 
<%
=end%>
      </div>
      <div class="mb-3">
        <%= form.label :detail, { class: "form-label"}  %><br>
        <%= form.text_field :detail, { class: "form-control", placeholder: "Enter Product Detail " } %><br>
        <%
=begin%>
 <% product.errors.full_messages_for(:detail).each do |message| %>
          <div><%= message %></div>
        <% end %> 
<%
=end%>
      </div>
      <div class="mb-3">
        <%= form.label :price, { class: "form-label"}  %><br>
        <%= form.number_field :price, { class: "form-control", placeholder: "Enter Product Price" }  %><br>
        <%
=begin%>
 <% product.errors.full_messages_for(:price).each do |message| %>
          <div><%= message %></div>
        <% end %> 
<%
=end%>
      </div> 
      <div class="mb-3"><br>
        <%= form.submit " Update ", { class: "btn btn-primary" }  %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container" style="height:870px;">
	<div>
    <h1 style="text-align:center">Welcome <%= @user_detail.role %> to Woo-commerce </h1>
		<h2 style="text-align:center">This is My Product </h2>
		<div class=row>
			<div class="col-1"></div>
			<div class="col-3">
				<h3>	
				<%=  link_to "new", new_user_product_path %>
				</h3>
			</div>
			<div class="col-6"></div>
			<div class="col-2">
				<h3><%= link_to 'Logout', '/logout', :data => { :confirm => 'Are you sure?' }%></h3>
			</div>
		</div>
		<hr>
	</div>
	<% if (@products.length).eql?(1) %>
		<div class="row">
			<div class="col-4"></div>
			<div class="col-4" style="margin-left:7%; margin-bottom:2.5%; margin-top:2.5%;">
				<h2><%= @products[0].name %></h2>
				<h5><%= @products[0].detail %> </h5>
				<h5><%= @products[0].price %>/-</h5>
				<h6>
					<%= link_to "Update", edit_user_product_path(@user, @products)  %>
				</h6>
			</div>
			<div class="col-4"></div>
		</div>
	<% elsif (@products.length > 1) %>
		<div class="row">
			<% @products.each do | product| %>
				<div class="col-3" style="margin-left:7%; margin-bottom:2.5%; margin-top:2.5%;">
					<h4><%= product.name %></h4>
					<p><%= product.detail %> </p>
					<b><%= product.price %>/-</b>
					<h6>
						<%= link_to "Update", edit_user_product_path(@user, product)  %>
					</h6>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/products/new.html.erb
<div class="container">
	<h1 style="text-align:center"> Add Your Product</h1><br>
	<%= form_with model: [:user,@product] do |form| %>
	<div class="card">
    <% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
    <% end %>
 		<div class="card-body">
      <div class="mb-3">
        <%= form.label :name, { class: "form-label"}  %><br>
        <%= form.text_field :name, { class: "form-control", placeholder: "Enter Product Name" } %><br>
        <%
=begin%>
 <% product.errors.full_messages_for(:name).each do |message| %>
          <div><%= message %></div>
        <% end %> 
<%
=end%>
      </div>
      <div class="mb-3">
        <%= form.label :detail, { class: "form-label"}  %><br>
        <%= form.text_field :detail, { class: "form-control", placeholder: "Enter Product Detail " } %><br>
        <%
=begin%>
 <% product.errors.full_messages_for(:detail).each do |message| %>
          <div><%= message %></div>
        <% end %> 
<%
=end%>
      </div>
      <div class="mb-3">
        <%= form.label :price, { class: "form-label"}  %><br>
        <%= form.number_field :price, { class: "form-control", placeholder: "Enter Product Price" }  %><br>
        <%
=begin%>
 <% product.errors.full_messages_for(:price).each do |message| %>
          <div><%= message %></div>
        <% end %> 
<%
=end%>
      </div>
      <div class="mb-3">
        <%= form.label :product_image, { class: "form-label"}  %><br>
        <%= form.file_field :product_image %>
      </div>

      <div class="mb-3"><br>
        <%= form.submit "Add Product", { class: "btn btn-primary" }  %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container" style="auto;">
	<div class="row">
		<div class="col-1">
			<h3><%= link_to "Back", root_path %></h3>
		</div>
    	<div class="col-10">
				<h1 style="text-align:center">This is about Product </h1>
			</div>
			<div class="col-1" style="text-align:left;">
				<h3><%= link_to 'Logout', '/logout', :data => { :confirm => 'Are you sure?' }%></h3>
			</div>
			<hr>
	</div>
	<% if current_user.role == "customer" %>
		<div class="row">
			<div class="col-11"></div>
			<div class="col-1">
				<b><%= link_to "My Orders", user_product_orders_path(product_id:@product.id) %></b>
			</div>
		</div>
	<% end %>
	<div class="row">
			<div class="col-4"></div>
			<div class="col-4" style="margin-top:2.5%;">
				<%= @product.product_image.each do |file|  %>
					<% if file.representable? %>
						<%= image_tag file.representable(resize_to_limit: [100, 100]) %>
					<% end %>
				<% end %>	
				<h2><%= @product.name %></h2>
				<h4><%= @product.detail %> </h4>
				<h5><%= @product.price %>/-</h5>
				<% if @user_detail.role == "customer" %>
					<b><%= link_to "Buy", new_user_product_order_path(product_id: @product.id) %><b>
				<% else %>
				<p  style="text-align:left">
					<%= link_to "Back", root_path %>
				</p>
				<p style="text-align:left" >
					<%=  link_to "My Products", user_products_path(current_user.id) %>
				</p>
				<% end %>
			</div>
			<div class="col-4"></div>
	</div>
</div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
<div class="card">
 <div class="card-body">
  <div class="mb-3">
    <%= form.label :name, { class: "form-label"}  %><br>
    <%= form.text_field :name, { class: "form-control", placeholder: "Enter Your Name" } %><br>
    <% user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div class="mb-3">
    <%= form.label :email, { class: "form-label"}  %><br>
    <%= form.email_field :email, { class: "form-control", placeholder: "Enter Your Email" } %><br>
    <% user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div class="mb-3">
    <%= form.label :role, { class: "form-label"}  %><br>
    <%= form.select :role, ["customer", "seller"], { class: "form-control" }  %>
  </div>
  <div class="mb-3">
    <%= form.label :password, { class: "form-label"}  %><br>
    <%= form.password_field :password, { class: "form-control", placeholder: "Enter Your Password" }  %><br>
    <% user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div> 
  <div class="mb-3">
    <%= form.label :password_confirmation, { class: "form-label"}  %><br>
    <%= form.password_field :password_confirmation, { class: "form-control", placeholder: "Confirm Your Password" }  %><br>
    <% user.errors.full_messages_for(:password_confirmation).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div class="mb-3"><br>
    <%= form.submit "Register", { class: "btn btn-primary" }  %>
  </div>
<% end %>
  <div>
      <a href="/login">Already have account</a>
  </div>
</div>
</div>

app/views/users/index.html.erb
<div class="container" style="height:870px; border:1px solid #800000; color:#800080;">
  <br>
  <div class="row" style="text-align:center">
    <h1>Welcome to Woo-commerce</h1>
    <hr>
  </div>
<div>

app/views/users/new.html.erb
<div class="container">
  <h2 style="text-align:center;">New User</h2>
  <%= render "form", user: @user %>
</div>

app/views/welcome/welcome.html.erb
<div class="container">
	<div>
		<h1 style="text-align:center;"> Welcome to Woo-commerce <h1>
		<hr>
	</div>
	<div class="row" style="text-align:center">
	<% if flash[:notice] %>
			<div class="message"><p><%= flash[:notice] %></p></div>
  	<% end %>
	</div>
	<div> 
<% if current_user %>
		<div class="row">
    	<div class="col-1"></div>
			<% if current_user.role == "seller" %>
				<h4 class="col-4">	
				<%=  link_to "new", new_user_product_path(current_user.id) %>
				</h4>
				<h4 class="col-4">	
					<%=  link_to "My Products", user_products_path(current_user.id) %>
				</h4>
				<div class="col-3">
					<h3><%= link_to 'Logout', '/logout', :data => { :confirm => 'Are you sure?' }%></h3>
				</div>
				<hr>
			<% else %>
				<div class="col-4"></div>
				<div class="col-4"></div>
				<div class="col-3">
					<h3><%= link_to 'Logout', '/logout', :data => { :confirm => 'Are you sure?' }%></h3>
				</div>
				<hr>
			<% end %>
		</div>
		<div class="row">
			<% @products.each do |product| %>
				<div class="col-3" style="margin-left:7%; margin-bottom:2.5%; margin-top:2.5%;">
				<%= product.product_image.each do |file|  %>
					<% if file.representable? %>
						<%= image_tag file.representable(resize_to_limit: [100, 100]) %>
					<% end %>
				<% end %>	
					<h4><%= link_to product.name, user_product_path(user_id:current_user.id,id: product.id) %></h4>
					<p><%= product.detail %> </p>
					<b><%= product.price %>/-</b>
				</div>
			<% end %>
		</div>
	</div>
	<div>
<% else %>
		<div style="text-align:center;">
			<h2><%= link_to 'Signup', '/signup'%></h2>
    	<h2><%= link_to 'Login', '/login'%></h2>
		</div>
		<div class="row">
		<% @products.each do |product| %>
			<div class="col-3" style="margin-left:7%; margin-bottom:2.5%; margin-top:2.5%;">
				<h4><%= product.name %></h4>
				<p><%= product.detail %> </p>
				<b><%= product.price %>/-</b>
			</div>
		<% end %>
		</div>
		<div class="container mt-5" style="text-align:center">
    <h3>You can Buy and Sale Products here</h3><br>
  	</div>
  	<div class="container mt-5">
      <div class="row">
          <div class="col-sm-6"><h3>As a Seller</h3></div>
          <div class="col-sm-6">
            <h5>Seller</h5>
            <ul class="list-group">
              <li class="list-group-item">Seller can add Products</li>
              <li class="list-group-item">Seller can See Products</li>
              <li class="list-group-item">Seller can change Products</li>
              <li class="list-group-item">Seller can update Products</li>
              <li class="list-group-item">Seller can not Buy Products</li>
            </ul>
          </div>
      </div>
  	</div>
  	<div class="container mt-5">
    	<div class="row">
      	<div class="col-sm-6"><h3>As a Customer</h3></div>
      	<div class="col-sm-6">
        	<h5>Customer</h5>
        	<ul class="list-group">
          	<li class="list-group-item">User can See All Products</li>
          	<li class="list-group-item">User can See All detail of Product</li>
          	<li class="list-group-item">User can Buy Product</li>
          	<li class="list-group-item">User see his/her parchased list</li>
          	<li class="list-group-item">User can not Add Products</li>
        	</ul>
      	</div>
    	</div>
  	</div>
<% end %>
	</div>
</div>